### ISSUE TITLE
Kan een onderwerp tegelijk een Zaakhandeling, VaststellingVergundeToestand, RechterlijkeUitspraak, BestuurlijkeRechtshandeling, InstellingBeroep, Aanvraag en Rechtshandeling zijn en een voorwerp tegelijk een <http://fixme.com#Rechtssubject>, PublicOrganisation en Rechtscollege?

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#11]
Afgaand op het vocabularium zou ik denken van wel.

```
<https://data.vlaanderen.be/ns/omgevingsvergunning#verantwoordelijke> a owl:ObjectProperty;
  rdfs:label "verantwoordelijke"@nl,
    "rechtscollege"@nl,
    "verzoekende partij"@nl,
    "aanvrager"@nl;
  rdfs:comment "De Publieke Organisatie verantwoordelijk voor het bepalen van de Vergunde Toestand."@nl,
    "Partij die het Rechtsmiddel aanwendt."@nl,
    "Rechtssubject of rechtssubjecten die de aanvraag indient(-en) of namens wie deze wordt ingediend."@nl,
    "Rechtssubject dat juridisch verantwoordelijk is voor de Rechtshandeling."@nl;
  rdfs:domain <https://data.vlaanderen.be/ns/omgevingsvergunning#Zaakhandeling>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#VaststellingVergundeToestand>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#RechterlijkeUitspraak>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#BestuurlijkeRechtshandeling>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#InstellingBeroep>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#Aanvraag>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#Rechtshandeling>;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/omgevingsvergunning>;
  rdfs:range <http://fixme.com#Rechtssubject>,
    <http://data.europa.eu/m8g/PublicOrganisation>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#Rechtscollege> .
```
Waarom wordt er een domein en range gedefinieerd? Dat is toch niet nodig?
In html-versie van het vocabularium lijkt het alsof de property verantwoordelijke meerdere keren is gedefinieerd (wat natuurlijk niet kan)

**Comment by saxomoose** [comment]
Disambiguatie naar:

- https://data.vlaanderen.be/ns/omgevingsvergunning#BestuurlijkeRechtshandeling.verantwoordelijke
- https://data.vlaanderen.be/ns/omgevingsvergunning#Rechtshandeling.verantwoordelijke
- https://data.vlaanderen.be/ns/omgevingsvergunning#VaststellingVergundeToestand.verantwoordelijke
- https://data.vlaanderen.be/ns/omgevingsvergunning#Zaak.verantwoordelijke
- https://data.vlaanderen.be/ns/omgevingsvergunning#Zaakhandeling.verantwoordelijke

**Comment by gezever** [comment]
Zoiets willen we dus niet

**Comment by pieterfa** [comment]
@gezever De property 'rechtscollege' in het vocabularium is ook overbodig. Hier kan dezelfde property 'verantwoordelijke' voor gebruikt worden. In het applicatieprofiel kan er aangegeven worden dat de range een Rechtscollege is.

**Comment by saxomoose** [comment]
`https://data.vlaanderen.be/ns/omgevingsvergunning#verantwoordelijke` wordt gebruikt als URI waar nodig.
