### ISSUE TITLE
Kan een subject tegelijk een Beroepsmogelijkheid en een Procedure zijn?

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#12]
Het vocabularium zegt van wel.

```
<https://data.vlaanderen.be/ns/omgevingsvergunning#bevoegdeOverheid> a owl:ObjectProperty;
  rdfs:label "bevoegde overheid"@nl;
  rdfs:comment "De Publieke Organisatie bevoegd om zich over het Rechtsmiddel uit te spreken."@nl,
    "De Publieke Organisatie bevoegd om zich over de Procedure uit te spreken."@nl;
  rdfs:domain <https://data.vlaanderen.be/ns/omgevingsvergunning#Beroepsmogelijkheid>,
    <https://data.vlaanderen.be/ns/omgevingsvergunning#Procedure>;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/omgevingsvergunning>;
  rdfs:range <http://data.europa.eu/m8g/PublicOrganisation> .
```
Waarom wordt er een domein gedefinieerd?
In html lijkt het alsof de property <https://data.vlaanderen.be/ns/omgevingsvergunning#bevoegdeOverheid> twee keer is gedefinieerd (wat natuurlijk niet kan)
![2024-06-12-16-16-11](https://github.com/Informatievlaanderen/OSLOthema-omgevingsvergunning/assets/28095014/088bf5cf-79c1-4eb3-81d8-5dfc1fcb007c)

**Comment by saxomoose** [comment]
Gewijzigd naar https://data.vlaanderen.be/ns/omgevingsvergunning#Beroepsmogelijkheid.bevoegdeOverheid).

Relatie organisatie:PubliekeOrganisatie omgevingsvergunning:Procedure is many-to-many. Hernoemd naar https://data.vlaanderen.be/ns/omgevingsvergunning#publiekeOrganisatie.

**Comment by gezever** [comment]
@saxomoose 
Deze oplossing wil ik niet.
Verwijder gewoon het domein aub

**Comment by pieterfa** [comment]
Het is niet nodig om hier 2 verschillende properties voor te definieren in het vocabularium. In beide gevallen verwijzen ze naar de bevoegde overheden.

**Comment by pieterfa** [comment]
@gezever Een andere bemerking hier. Is dit ook geen many-to-many relatie op Beroepsmogelijkheid (subklasse van Procedurestap) ?

**Comment by saxomoose** [comment]
URI `https://data.vlaanderen.be/ns/omgevingsvergunning#bevoegdeOverheid` wordt gebruikt als gemeenschappelijke URI. Attribuut omgezet naar associatie.
