### ISSUE TITLE
Is een Vergunning, een Aanvraag of een InstellingBeroep een soort Event?

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#13]
Valt een vergunning onder volgende definitie?:

"An event happening at a certain time and location, such as a concert, lecture, or festival. Ticketing information may be added via the [offers](https://schema.org/offers) property. Repeated events may be structured as separate Event objects."

**Comment by saxomoose** [comment]
generiek:Gebeurtenis hermapped naar http://data.europa.eu/m8g/Event.

**Comment by gezever** [comment]
It is not expected to be used directly, rather, one or other of its subclasses should be used.

i.e. BusinessEvent of LifeEvent

**Comment by gezever** [comment]
Event gaat uit het model,
zie https://github.com/Informatievlaanderen/OSLOthema-omgevingsvergunning/issues/38

**Comment by saxomoose** [comment]
Fixed
