### ISSUE TITLE
https://data.vlaanderen.be/ns/omgevingsvergunning#Waarmerk

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#17]
https://data.vlaanderen.be/ns/omgevingsvergunning#Waarmerk wordt vermeld in de shacl, maar is niet gedefinieerd in het vocabularium.

**Comment by saxomoose** [comment]
Deze uitbreiding dient op OSLO Generiek te gebeuren waar Document reeds gedefinieerd staat. Wordt mee opgenomen voor de herpublicatie van OSLO Generiek.

**Comment by gezever** [comment]
@saxomoose 
Dit issue gaat over Waarmerk, binnen het vocabularium van omgevingsvergunning en heeft niets met Document of generiek te maken.

**Comment by saxomoose** [comment]
Eerst beslissen welke aanknopingspunt wordt gebruikt. `foaf:Document`, `dossier:Stuk` of andere. Waarmerk als datastructuur met bijv. een elektronische verzegelingstimestamp / ondertekeningstimestamp lijkt me alleszins meer op zijn plaats in OSLO Generiek / OSLO Dossier.

**Comment by saxomoose** [comment]
In samenspraak met kernteam, `omgevingsvergunning:Document` ingevoerd met volgende definitie: "Logisch geheel van informatie vastgelegd op een gegevensdrager in welke vorm ook."

**Comment by saxomoose** [comment]
#27 resolved via http://www.w3.org/ns/prov#atLocation → http://www.w3.org/ns/prov#Location

**Comment by saxomoose** [comment]
Reverted naar `foaf:Document` op voorstel van @bertvannuffelen
