### ISSUE TITLE
Ik denk niet dat we https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheid willen gebruiken

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#20]
**probleen**

```
<https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheid> a owl:Class;
  rdfs:label "Ruimtelijke Eenheid"@nl;
  <http://purl.org/vocab/vann/usageNote> "Definitie conform ISO 19152 - Land Administration Domain Model."@nl;
  rdfs:comment "Eén gebied (of meerdere gebieden) van land en/of water, of één enkel volume (of meerdere volumes) ruimte, afgebakend voor een bepaald doel."@nl;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/perceel> .

<https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheid.geometrie> a owl:ObjectProperty;
  rdfs:label "geometrie"@nl;
  rdfs:comment "Vorm- en positiekenmerken van een object."@nl;
  rdfs:domain <https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheid>;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/perceel>;
  rdfs:range <https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheidGeometrie> .

<https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheidGeometrie> a owl:Class;
  rdfs:label "Ruimtelijke Eenheid Geometrie"@nl;
  rdfs:comment "Geometrie van de ruimtelijke eenheid en metadata over hoe deze werd bepaald."@nl;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/perceel> .

<https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheidGeometrie.geometrie> a owl:ObjectProperty;
  rdfs:label "geometrie"@nl;
  rdfs:comment "Geometrische voorstelling van een ruimtelijke eenheid."@nl;
  rdfs:domain <https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheidGeometrie>;
  rdfs:isDefinedBy <https://data.vlaanderen.be/ns/perceel>;
  rdfs:range <http://www.w3.org/ns/locn#Geometry> .

```
Om een polygoon ergens aan te hangen, altijd een tussenklasse gaan gebruiken en twee properties "geometrie"? Ik denk het niet.

**oplossing**

```
  "geometrie": {
    "@id": "http://www.opengis.net/ont/geosparql#hasGeometry",
    "@type": "@id"
  }
```
**Conclusie**
https://data.vlaanderen.be/ns/perceel#RuimtelijkeEenheid wordt vervangen door http://www.opengis.net/ont/geosparql#Feature

**Comment by gezever** [comment]
Ook de Nederlandse overheid adviseert het gebruik van geosparql.
"Definitie conform [ISO 19152 - Land Administration Domain Model](https://wiki.icaci.org/index.php?title=ISO_19152:2012_Geographic_information_-_Land_Administration_Domain_Model_(LADM))." 
In dit document staat:
"The representations of spatial data conform to the spatial schema described in [ISO 19107:2003 Geographic information - Spatial schema](https://wiki.icaci.org/index.php?title=ISO_19107:2003_Geographic_information_-_Spatial_schema)."
Over ISO 19107 zegt de Nederlandse overheid het volgende:
"Men zou verwachten dat bijvoorbeeld het spatial schema, 19107, het model van geometrietypen een bruikbaar [RDF](https://docs.geostandaarden.nl/nen3610/nldp/#dfn-rdf) vocabulaire zou opleveren. Hier wordt echter aan getwijfeld en men adviseert het gebruik van al bestaand [RDF](https://docs.geostandaarden.nl/nen3610/nldp/#dfn-rdf)-vocabulaire op dit terrein, bijvoorbeeld GeoSPARQL."
https://docs.geostandaarden.nl/nen3610/nldp/

**Comment by gezever** [comment]
Gewenste oplossing:
![Feature](https://github.com/user-attachments/assets/3b847b1d-0d64-4820-b41f-47ed0e2af36e)

**Comment by saxomoose** [comment]
OSLO omgevingsvergunning moet verschillende strategiëen voor locatieaanduiding ondersteunen. Een daarvan is absolute positiebepaling via een geometrie. Vaak worden ook perceel identificatoren gebruikt als aanknopingspunt. Of semi-gestructureerde adressen.

In een eerste iteratie van het model, werd [prov:Location](https://www.w3.org/TR/prov-o/#Location) gebruikt als bovenliggende datastructuur. Lijkt meer aangewezen dan [geo:Feature](https://opengeospatial.github.io/ogc-geosparql/geosparql11/document.html#_class_geofeature) die verwijst naar datgene gesitueerd wordt. In ons geval komt dat laatste overeen met `omgevingsvergunning:Activiteit`.

**Comment by gezever** [comment]
De use case is hier om een geometrie en een oppervlakte aan iets te hangen. prov-o heeft hiervoor geen elementen. geosparql wel.  De betekenis van geo:Feature is analoog aan RuimtelijkeEenheid. De property adres komt voor als issue, waar ik locn:address voorstel ter vervanging van een onbestaande property. locn:address heeft geen domaindefinitie, dus dat kan perfect. locn:fullAddress, waar je een semi-gestructureerd adres in kwijt kan, heeft domain locn:Address, ook perfect. 
Wat betreft identificatoren voor perceel. De properties hiervoor moeten nog gemaakt worden, dus ik stel voor om dat meteen goed te doen en het domain als rdf:Resource te definieren.
