### ISSUE TITLE
conformiteit

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#22]
Onder [conformiteit](https://data.vlaanderen.be/doc/begeleidend/applicatieprofielen/conformiteit/) lees ik volgend statement.
Om conform te zijn met dit applicatieprofiel, geldt voor een implementatie dat ze:
MAG NIET terminologie van andere gecontroleerde vocabularia gebruiken dan diegene die gedefinieerd wordt in dit applicatieprofiel.

Wat betekent dit concreet?
bv. in shacl dat er closed true moet staan?
Indien niet, wat betekent het wel?

**Comment by bertvannuffelen** [comment]
Een Controlled Vocabulary (direct vertaald naar gecontroleerde vocabularia) is een codelijst.

Dat betekend dat opgegeven codelijsten moeten gevolgd worden door implementaties.
Aangezien er hier geen codelijsten worden opgelijst is dit een zin die niet van toepassing hier is.

Ivm conformiteit stel ik voor dat we dit gaan herwerken in lijn met het conformiteitsraamwerk. 
Dat is zinvoller.
