### ISSUE TITLE
Definitie https://data.vlaanderen.be/ns/omgevingsvergunning#locatie

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#23]
"Definitie 	Aanduiding van de plaats waar een Activiteit plaatsvindt, zal vinden, of zou hebben gevonden."

Zou hebben gevonden is voorwaardelijke wijs. Waarom deze voorwaardelijkheid?

**=> Aanduiding van de plaats waar een Activiteit plaatsvindt, plaats zal vinden, of plaatsvond.**

_Voor een bijzin:
- plaatsvindt (onvoltooid tegenwoordig)
- zal plaatsvinden of plaats zal vinden (onvoltooid toekomend)
- plaatsvond (onvoltooid verleden)
- heeft plaatsgevonden (voltooid tegenwoordig)
- had plaatsgevonden (voltooid verleden)
- zal plaatsgevonden hebben (voltooid toekomend)_

**Comment by PhR-VO** [comment]
Voorwaardelijke wijs is hier gebruikt met het oog op bijvoorbeeld vaststellingen of meldingen van activiteiten die **volgens de auteur** ergens zouden hebben plaatsgevonden. Daar zit een zekere mate van subjectiviteit in. Maar deze nuance is mogelijk te subtiel om er de definitie op af te stellen. Tegenvoorstel is voor mij oké.
