### ISSUE TITLE
Voorbeelden van instances van de klasse Procedure

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#25]
Een Procedure is de blauwdruk voor de afhandeling van een Zaak.
Wegens de subclassing ook:
cpsv:Rule
- The Rule class represents the specific rules, guidelines or procedures that the Public Service follows. Instances of the Rule class are FRBR Expressions, that is, a concrete expression, such as a document, of the more abstract concept of the rules themselves.
http://purl.org/vocab/frbr/core#Expression
- This class corresponds to the FRBR group one entity 'Expression'.
- A realization of a single work usually in a physical form.
http://purl.org/vocab/frbr/core#Endeavour
- This class represents any one of the FRBR group one entities.
- Any of the products of artistic or creative endeavour.

In het zakboekje van de milieucoordinator staat een overzicht van de omgevingsvergunningsprocedures. (paragraaf 2.4.)
Zijn dit de blauwdrukken voor de afhandeling van een zaak? 
Die omgevingsvergunningsprocedures zijn frbr:Expressions in de zin dat ze wetgeving beschrijven.

**Comment by saxomoose** [comment]
Een instance van een `omgevingsvergunning:Procedure` is bijv. de vereenvoudigde vergunningsprocedure zoals beschreven in het decreet betreffende de omgevingsvergunning.
