### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#26]
https://data.vlaanderen.be/ns/generiek#Document
is een 
http://xmlns.com/foaf/0.1/Document
Met de definitie:
The [Document](http://xmlns.com/foaf/spec/#term_Document) class represents those things which are, broadly conceived, 'documents'.
Dit is een circulaire definitie en is ongewenst.
Vandaar het bestaan van dossier:Stuk.

**Comment by saxomoose** [comment]
To be discussed under #17
