### ISSUE TITLE
Wat op het uml diagram 'datatypes' worden genoemd zijn klassen

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#3]
Verwijzing, Rechtsbronverwijzing, Zaakverwijzing, JuridischeCategorie, Locatie, ....

Voorstellen als klassen, onderdeel van het uml-diagram aub

**Comment by saxomoose** [comment]
Heeft betrekking tot een vorige iterate van het model.
Cf. #4.
