### ISSUE TITLE
Klasse Vordering en relatie met Rechtshandeling

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#34]
In het UML diagram staat de klasse Vordering als subklasse van Inhoud.

- Deze klasse is niet gedefinieerd in het vocabularium of het applicatieprofiel.
- De relatie met Rechtshandeling is niet benoemd

**Comment by saxomoose** [comment]
In samenspraak met kernteam, werd besloten om Vordering, VerzoekTotToelating en Toelating voor illustratieve doeleinden aan het diagram toe te voegen.

**Comment by gezever** [comment]
@saxomoose 
Is het dan niet de bedoeling dat we weten wat dit betekent?

**Comment by PhR-VO** [comment]
Verzoek tot toelating, toelating, weigering, vordering, schorsing, vernietiging, etc. zijn allemaal dingen die een rechtshandeling kan inhouden. Het zijn soorten inhoud van een rechtshandeling. In het model kan daar op twee manieren uitdrukking aan gegeven: als subklasse van Inhoud, of als aard/modaliteit (ontbreekt momenteel nog) van Inhoud. Om voor alle mogelijk vormen van Inhoud van een rechtshandeling definities vast te leggen in het vocabularium leidt ons nu te ver, denk ik. Een toelichting in usage notes (misschien  iets uitgebreider dan nu?) volstaat voor gebruik van het model en eventueel op termijn een uitbreiding met een codelijst voor de aard/modaliteit van Inhoud voor een optimalere interoperabiliteit.

**Comment by gezever** [comment]
@PhR-VO 
Bedankt voor de verduidelijking.
De verschillende soorten rechtshandelingen en inhouden uitbreidbaar typeren vanuit een lijst vind ik een goed idee. Modelleer en documenteer dit dan op die manier aub. Er is geen nood om dit als klassen uit te drukken.
