### ISSUE TITLE
Dode link in readme

### ISSUE THREAD

**Issue by PhR-VO** [Informatievlaanderen/OSLOthema-omgevingsvergunning#39]
README bevat een dode link. 
"De overeenkomstige overzichtspagina uit het standaardenregister is [hier](https://data.vlaanderen.be/standaarden/kandidaat-standaard/vocabularium-omgevingsvergunning.html) te vinden."

**Comment by KristofVDB1** [comment]
Dit is rechtgezet. Bedankt om dit te melden @PhR-VO !

**Comment by PhR-VO** [comment]
Ik zie nog steeds de dode link. Laatste update van de readme file dateert van 6 maanden geleden.

**Comment by KristofVDB1** [comment]
Mijn excuses. Je hebt gelijk. Ik had de link aangepast in het AP maar niet in de README. Bij deze wél in orde 👍

**Comment by PhR-VO** [comment]
in orde, bedankt.
