### ISSUE TITLE
JuridischeCategorie

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#44]
Niet laten subclassen van Juridisch werk aub.
Die categorien zijn niet altijd een juridisch werk, soms gewoon concepten die ik heb gemaakt.
[@PhR-VO](https://github.com/PhR-VO) en [@pieterfa](https://github.com/pieterfa), akkoord?

**Comment by pieterfa** [comment]
@gezever Akkoord. De juridische categorien worden in codelijsten gecapteerd. Het zijn skos concepten uit 1 of meerdere skos conceptschemas. Deze codelijsten kunnen wel vastgelegd en/of beschreven zijn in wetgeving (of juridische werken). Vanuit deze concepten (juridische categorien) kan er wel verwezen worden naar wetgeving (of juridische werken) (bv. via een prov:hadPrimarySource relatie, via een skos:note,...).
