### ISSUE TITLE
Tijdsaanduidingen

### ISSUE THREAD

**Issue by pieterfa** [Informatievlaanderen/OSLOthema-omgevingsvergunning#45]
### Tijdsduur vs TijdsInterval
Wat wordt met de klasse tijdsduur in dit applicatieprofiel juist bedoeld?

De Klasse Tijdsduur is gedefinieerd als http://www.w3.org/2006/time#Interval.
In de time ontology heb je een TijdsInterval (http://www.w3.org/2006/time#Interval) wat een tijdsaanduiding is met een omvang of duur en een Tijdsduur (http://www.w3.org/2006/time#TemporalDuration) wat de duur van een (Tijds)Interval aanduid.
Deze 2 worden door elkaar gebruikt in het applicatieprofiel:
- Eigenschap tijdsbestek op Activiteit en NormatieveBepaling: Tijdsduur of TijdsInterval? Hier wordt een TijdsInterval bedoeld vermoed ik, een concrete tijdsbepaling met een omvang en duur.
- Eigenschappen aanwendingstermijn (op Beroepsmogelijkheid subklasse van Procedurestap) en termijn (op Procedure): Tijdsduur of TijdsInterval? Hier wordt een termijn en dus een Tijdsduur bedoeld vermoed ik.

Voorstel: Definieer de 2 klassen: Tijdsduur als http://www.w3.org/2006/time#TemporalDuration en TijdsInterval als http://www.w3.org/2006/time#Interval

### Tijdsduurbeschrijving (http://www.w3.org/2006/time#DurationDescription)

- Dit is geen subklasse van http://www.w3.org/2006/time#Interval maar wel van http://www.w3.org/2006/time#TemporalDuration.
- De eigenschappen die in het applicatieprofiel gedefinieerd staan op deze klasse, tijdseenheid (http://www.w3.org/2006/time#unitType) en waarde (http://www.w3.org/2006/time#numericDuration), zijn eigenschappen met als domein http://www.w3.org/2006/time#Duration (en niet DurationDescription)

Wat is er in dit applicatieprofiel gewenst voor het aanduiden van een Tijdsduur? Zijn er specifieke eisen om een duur aan te duiden?

### Datum

- Datum is als een http://www.w3.org/2001/XMLSchema#date gedefinieerd maar ook als subklasse van Tijdstip (http://www.w3.org/2006/time#Instant)? Kan dit?

Soms is de verwachte range van een eigenschap Tijdstip soms Datum? Wat is hier juist de bedoeling? Zie oplijsting hieronder:
- Klasse https://data.vlaanderen.be/doc/applicatieprofiel/omgevingsvergunning/#Rechtsgrond
buitenwerkingtreding: Datum (1)
inwerkingtreding: Datum (1)
-  Klasse https://data.vlaanderen.be/doc/applicatieprofiel/omgevingsvergunning/#Rechtshandeling
ingangsdatum: Datum (1) (e.g. datum arrest)
-  Klasse https://data.vlaanderen.be/doc/applicatieprofiel/omgevingsvergunning/#VaststellingVergundeToestand
vaststellingtijdstip: Tijdstip (0..1) (Tijdstip van vaststelling)
-  Klasse https://data.vlaanderen.be/doc/applicatieprofiel/omgevingsvergunning/#VergundeToestand
toestand datum: Datum (0..1) Aanduiding van de datum van de Vergunde Toestand.

**Comment by saxomoose** [comment]
Tijdsduur vastgelegd op `http://www.w3.org/2006/time#TemporalDuration`.
Tijdsinterval vastgelegd op `http://www.w3.org/2006/time#Interval`

Overerving tussen `xsd:date` en `time:Instant` verwijderd.
Er wordt enkel gewerkt met `xsd:date` en `xsd:dateTime`.
