### ISSUE TITLE
Property verantwoordelijke en afgeleiden hiervan

### ISSUE THREAD

**Issue by pieterfa** [Informatievlaanderen/OSLOthema-omgevingsvergunning#47]
Voor de eigenschap rechtscollege moet geen nieuwe property in het vocabularium gedefinieerd worden. Dezelfde rdf property als die voor de eigenschap verantwoordelijke op zijn parent klasse (Rechtshandeling) en 'sibling' klasse (BestuurlijkeRechtshandeling) kan hier gebruikt worden. In het applicatieprofiel kan je als range Rechtscollege aangeven.

Hetzelfde geldt ook voor verzoekendePartij en aanvrager. Niet?

**Comment by saxomoose** [comment]
Cf. #11
