### ISSUE TITLE
Properties termijn en aanwendingstermijn

### ISSUE THREAD

**Issue by pieterfa** [Informatievlaanderen/OSLOthema-omgevingsvergunning#48]
Het volstaat om slechts 1 van deze 2 properties te definieren in het vocabularium:

- https://data.vlaanderen.be/ns/omgevingsvergunning#termijn
- https://data.vlaanderen.be/ns/omgevingsvergunning#aanwendingstermijn

**Comment by saxomoose** [comment]
URI `https://data.vlaanderen.be/ns/omgevingsvergunning#termijn` wordt gebruikt als gemeenschappelijke URI.
