### ISSUE TITLE
beroepsmogelijkheid vs beroepsprocedure

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgevingsvergunning#50]
Indien een beroepsmogelijkheid een procedurestap is,
```turtle
@prefix omv: <https://data.vlaanderen.be/ns/omgevingsvergunning#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
omv:Beroepsmogelijkheid a owl:Class;
    <http://purl.org/vocab/vann/usageNote> "Mogelijkheid om in beroep te gaaan tegen een gemeentelijke vergunningsbeslissing in eerste aanleg. Of jurisdictioneel beroep tegen een beslissing in laatste administratieve aanleg."@nl;
    rdfs:comment "Procedure die de mogelijkheid biedt om een bestuurlijke rechtshandeling of gerechtelijke beslissing aan te vechten."@nl;
    rdfs:isDefinedBy <https://data.vlaanderen.be/ns/omgevingsvergunning>;
    rdfs:subClassOf omv:Procedurestap.
```
Waarom is dit dan in tekst als Procedure gedefinieerd?

Ik heb altijd verdedigd dat een behandeling in hogere administratieve aanleg een nieuwe zaak is, wegens een nieuwe procedure. (Terecht is de kardinaliteit op omv:procedure max 1)
Het omgevingsvergunningendecreet spreekt ook van een beroepsprocedure.
https://navigator.emis.vito.be/detail?woId=65413

**Comment by saxomoose** [comment]
Definitietekst aangepast naar "Procedure<ins>stap</ins> die de mogelijkheid biedt om een bestuurlijke rechtshandeling of gerechtelijke beslissing aan te vechten."
